// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yroueuznkqlltozpqpru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyb3VldXpua3FsbHRvenBxcHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMjYyMjgsImV4cCI6MjA3ODgwMjIyOH0.tU--qPD1W7eQi_9jG-VAD5M897YHraJFUqpApZyWBrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});