// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnbnboiwqcghsephthsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYm5ib2l3cWNnaHNlcGh0aHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMzE2OTMsImV4cCI6MjA3NzYwNzY5M30.gm4UCkdK_fOc7rSeRof0J5hz9D06fiE9N0wb9H-vSvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});